### ISSUE TITLE
Reproducing Figure 3 and 4 from the original paper

### ISSUE THREAD

**Issue by falexwolf** [GGiecold/ECLAIR#2]
Hi!

I wanted to reproduce Figure 3 and 4 from the Nucleic Acids Research [paper](https://doi.org/10.1093/nar/gkw452) but I'm struggling already at finding and providing the data in the correct form.

Is it possible to generate a minimal example where you reproduce these figures and provide the data files or links to the data files?

Thank you,
  Alex

PS: Actually, I didn't find a single usage example that allows to quickly reproduce a tree from a given dataset.

**Comment by GGiecold** [comment]
Hi Alex,

After a 2-year stint in computational biology, I have moved on to other
endeavors. You should ask Sara Garcia for help. Figures 3 & 4 were added at
the request of our reviewer.

Regarding your post-scriptum, the README file in ECLAIR's GitHub repository
explains how to automatically process a dataset, and generate those lineage
trees. Unfortunately, with endless haggling on how much "technical"
information to add to the draft, this was ultimately omitted in the
published version of our work.

With kind regards,

Gregory

**Comment by falexwolf** [comment]
Hi Gregory,

thanks for your response! Unfortunately, I can't figure out how to contact Sara; neither your former [lab](http://bcb.dfci.harvard.edu/~gcyuan/people.html) nor another page that google could find list an email address. Do you have it?

Cheers,
  Alex

**Comment by GGiecold** [comment]
Hi Alex,

Sara has taken a research staff position at Massachusetts General Hospital.
In case they cut off her former account (sgarcia@jimmy.harvard.edu), you
can reach her at sara.pinto.garcia@gmail.com
or sara_pinto_garcia@hotmail.com

She's been following your work and that of Theis.

With kind regards,

Gregory

**Comment by falexwolf** [comment]
Thank you! 😄
